"""create asset maintenance tables

Revision ID: 1ded697490a9
Revises: <base>
Create Date: 2026-09-29 23:55:49.603453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ded697490a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=80), nullable=False),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('last_inspected_on', sa.Date(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_due', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_table('triage_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_runs_evaluated_on'), 'triage_runs', ['evaluated_on'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspected_on', sa.Date(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_records_asset_id'), 'inspection_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_inspected_on'), 'inspection_records', ['inspected_on'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned', sa.Boolean(), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_asset_id'), 'maintenance_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_event_date'), 'maintenance_records', ['event_date'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=False),
    sa.Column('asset_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['triage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'asset_id')
    )
    op.create_index(op.f('ix_recommendations_asset_id'), 'recommendations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_recommendations_evaluated_on'), 'recommendations', ['evaluated_on'], unique=False)
    op.create_index(op.f('ix_recommendations_risk_level'), 'recommendations', ['risk_level'], unique=False)
    op.create_index(op.f('ix_recommendations_run_id'), 'recommendations', ['run_id'], unique=False)
    op.create_table('recommendation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_events_event_type'), 'recommendation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_recommendation_events_recommendation_id'), 'recommendation_events', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_events_recommendation_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_event_type'), table_name='recommendation_events')
    op.drop_table('recommendation_events')
    op.drop_index(op.f('ix_recommendations_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_risk_level'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_evaluated_on'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_asset_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_maintenance_records_event_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_asset_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_inspection_records_inspected_on'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_asset_id'), table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_triage_runs_evaluated_on'), table_name='triage_runs')
    op.drop_table('triage_runs')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
